version: '3.8'

services:
  web-tests:
    build: .
    container_name: web-testing-suite
    volumes:
      - ./reports:/app/reports
      - ./tests:/app/tests
    environment:
      - CI=true
    command: pytest tests/ -v --html=reports/test-report.html --self-contained-html
    networks:
      - test-network

  performance-tests:
    build: .
    container_name: performance-testing
    ports:
      - "8089:8089"
    volumes:
      - ./reports:/app/reports
      - ./tests/performance:/app/tests/performance
    working_dir: /app/tests/performance
    command: locust -f locustfile.py --host=https://www.saucedemo.com --web-host=0.0.0.0
    networks:
      - test-network

  security-scan:
    build: .
    container_name: security-scanner
    volumes:
      - ./reports:/app/reports
    command: >
      sh -c "
        pip install bandit safety &&
        bandit -r . -f json -o reports/bandit-report.json &&
        safety check --json --output reports/safety-report.json &&
        echo 'Security scan completed. Check reports/ directory for results.'
      "
    networks:
      - test-network

networks:
  test-network:
    driver: bridge

volumes:
  reports:
    driver: local